version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - CONFIGURATION=production
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    depends_on:
      - database
      - minio
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=appdb;Username=user;Password=password
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=minioadmin
      - MinIO__SecretKey=minioadmin
      - MinIO__BucketName=uploads
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - Jwt__Key=your-super-secret-jwt-key-here
      - Jwt__Issuer=https://vtobackend.marthand.org
      - Jwt__Audience=https://vtobackend.marthand.org
      - API_BASE_URL=https://vtobackend.marthand.org
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: