version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - BUILD_COMMAND=npm run build:prod
    ports:
      - "8080:80"
    depends_on:
      - backend
    command: nginx -g 'daemon off;'
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      args:
        - BUILD_COMMAND=dotnet publish -c Release -o out
    ports:
      - "3000:3000"
    depends_on:
      - database
      - minio
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=appdb;Username=user;Password=password
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=minioadmin
      - MinIO__SecretKey=minioadmin
      - MinIO__BucketName=uploads
      - ASPNETCORE_ENVIRONMENT=Production
    command: dotnet out/YourApp.dll
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: